backend/models/User.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "user".
 *
 * @property integer $id
 * @property string $username
 * @property string $auth_key
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 *
 * @property Article[] $articles
 * @property ArticleComment[] $articleComments
 * @property Booking[] $bookings
 * @property BookingComment[] $bookingComments
 * @property Event[] $events
 * @property Event[] $events0
 * @property EventComment[] $eventComments
 * @property News[] $news
 * @property NewsComment[] $newsComments
 * @property Preferences[] $preferences
 * @property Ticket[] $tickets
 * @property Ticket[] $tickets0
 * @property TicketComment[] $ticketComments
 * @property UsersAirports[] $usersAirports
 */
class User extends \common\models\EstData
{

    const STATUS_ACTIVE = 1;

    const ROLE_ADMIN = 2;
    const ROLE_CLIENT = 1;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'auth_key', 'password_hash', 'email', 'created_at', 'updated_at'], 'required'],
            [['status'], 'integer'],
            [['email'], 'email'],
            [['status'], 'default', 'value' => self::STATUS_ACTIVE],
            [['role'], 'integer'],
            [['role'], 'default', 'value' => self::ROLE_CLIENT],
            [['created_at', 'updated_at'], 'safe'],
            [['username', 'password_hash', 'password_reset_token', 'email'], 'string', 'max' => 255],
            [['auth_key'], 'string', 'max' => 32]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'auth_key' => 'Auth Key',
            'password_hash' => 'Password Hash',
            'password_reset_token' => 'Password Reset Token',
            'email' => 'Email',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticles()
    {
        return $this->hasMany(Article::className(), ['admin_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticleComments()
    {
        return $this->hasMany(ArticleComment::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBookings()
    {
        return $this->hasMany(Booking::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBookingComments()
    {
        return $this->hasMany(BookingComment::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvents()
    {
        return $this->hasMany(Event::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvents0()
    {
        return $this->hasMany(Event::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEventComments()
    {
        return $this->hasMany(EventComment::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNews()
    {
        return $this->hasMany(News::className(), ['admin_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNewsComments()
    {
        return $this->hasMany(NewsComment::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPreferences()
    {
        return $this->hasMany(Preferences::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTickets()
    {
        return $this->hasMany(Ticket::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTickets0()
    {
        return $this->hasMany(Ticket::className(), ['admin_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTicketComments()
    {
        return $this->hasMany(TicketComment::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsersAirports()
    {
        return $this->hasMany(UsersAirports::className(), ['user_id' => 'id']);
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\User;
use backend\models\search\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
			'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'view', 'create', 'delete','update'],
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'delete','update'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            return !Yii::$app->user->isGuest && Yii::$app->user->identity->role==2;
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $user = $this->findModel($id);
        $user->deleted = User::DELETED;
        $user->save(false);

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne(['id' => $id, 'deleted' => \common\models\EstData::NOT_DELETED, 'archived' => \common\models\EstData::NOT_ARCHIVED])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/UserController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\User;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\adapters\FaregrabbrTripSearch;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\ConfirmDeletionForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    // public function behaviors()
    // {
    //     return [
    //         'verbs' => [
    //             'class' => VerbFilter::className(),
    //             'actions' => [
    //                 'delete' => ['post'],
    //             ],
    //         ],
    //     ];
    // }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionAccount()
    {

        $model = Yii::$app->user->identity;

        return $this->render('account', [
            'model' => $model,
        ]);
    }


    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate()
    {
        $model = Yii::$app->user->identity;

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->save()) {
                return $this->redirect(['account']);
            } else {
                Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to update your account. Please contact an admin if the problem persists. Thank you.');
            }
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionTrips()
    {
        // feature not yet support by API
        Yii::$app->getSession()->setFlash('error', 'Feature not yet supported by our API.');
        return $this->goBack();
    }

    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            if ($model->email === Yii::$app->user->identity->email) {
                if ($model->sendEmail()) {
                    Yii::$app->getSession()->setFlash('success', 'Please check your email for further instructions.');
                    return $this->goHome();
                } else {
                    Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
                }
            } else {
                    Yii::$app->getSession()->setFlash('error', 'Sorry, this is not the e-mail you are currently logged in with. Please check again or if you wish to change your e-mail please contact an admin by creating a new Support Ticket.');
            }

        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'Your password has been changed succesfully.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function actionDelete($id)
    {
        $model = new ConfirmDeletionForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->email === Yii::$app->user->identity->email) {
                if ($model->deleteUser(Yii::$app->user->id)) {
                    Yii::$app->user->logout();
                    Yii::$app->getSession()->setFlash('success', 'Your account has been deleted succesfully.');
                    return $this->goHome();
                } else {
                    Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to delete your account at this time. Please contact an admin by using our Support Ticket system. Thank you.');
                }
            } else {
                    Yii::$app->getSession()->setFlash('error', 'Sorry, this is not the e-mail you are currently logged in with. Please check again or if you wish to change your e-mail please contact an admin by creating a new Support Ticket.');
            }
        }

        return $this->render('confirmDeletion.php', [
            'model' => $model,
        ]);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne(['id' => $id, 'deleted' => \common\models\EstData::NOT_DELETED, 'archived' => \common\models\EstData::NOT_ARCHIVED])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\datepicker\DatePicker;
use kartik\select2\Select2;
use yii\web\JsExpression;
use common\models\Airport;

/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $form yii\widgets\ActiveForm */

$airport_url = \yii\helpers\Url::to(['airport/ajax-list']);
$country_url = \yii\helpers\Url::to(['country/ajax-list']);
if ($model->airport) {
	$airport = $model->airport->name . ", " . $model->airport->city . ", " . $model->airport->country . " - " . $model->airport->iata_code;
} else {
	$airport = "";
}

?>

<div class="user-form">
	<div class="row">
		<div class="col-xs-12 col-sm-8 col-sm-offset-2">
				
		    <?php $form = ActiveForm::begin(['class' => 'row']); ?>

		    <?= $form->field($model, 'firstname', ['options' => ['class' => 'col-sm-4']])->textInput(['maxlength' => true]) ?>
		    <?= $form->field($model, 'middlename', ['options' => ['class' => 'col-sm-4']])->textInput(['maxlength' => true]) ?>
		    <?= $form->field($model, 'lastname', ['options' => ['class' => 'col-sm-4']])->textInput(['maxlength' => true]) ?>
		    <?= $form->field($model, 'date_of_birth', ['options' => ['class' => 'col-sm-4']])->widget(DatePicker::className(),[
			        // inline too, not bad
			         // 'inline' => true,
			         // modify template for custom rendering
			        // 'template' => '<div class="well well-sm" style="background-color: #fff; width:250px">{input}</div>',
			        'clientOptions' => [
			            // 'autoclose' => true,
			            'format' => 'yyyy-mm-dd'
			        ]
		    ])->label('Date of Birth (yyyy-mm-dd)') ?>
		    <?= $form->field($model, 'gender', ['options' => ['class' => 'col-sm-3']])->dropDownList(['M' => 'M', 'F' => 'F']) ?>
		    <?= $form->field($model, 'country_id', ['options' => ['class' => 'col-sm-5']])->widget(Select2::classname(), [
				    'pluginOptions' => [
				        'allowClear' => true,
				        'minimumInputLength' => 3,
				        'language' => [
				            'errorLoading' => new JsExpression("function () { return 'Waiting for results...'; }"),
				        ],
				        'ajax' => [
				            'url' => $country_url,
				            'dataType' => 'json',
				            'data' => new JsExpression('function(params) { return {q:params.term}; }')
				        ],
				        'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
				        'templateResult' => new JsExpression('function(country) { return country.name; }'),
				        'templateSelection' => new JsExpression('function (country) { return country.name; }'),
				    ],
				]); 

			?>
		    <?= $form->field($model, 'phone', ['options' => ['class' => 'col-sm-4']])->textInput(['maxlength' => true]) ?>
		    <?= $form->field($model, 'airport_id', ['options' => ['class' => 'col-sm-8']])->widget(Select2::classname(), [
				    'initValueText' => $airport, // set the initial display name
				    // 'theme' => Select2::THEME_DEFAULT,
				    // 'options' => ['placeholder' => 'Your preferred airport ...'],
				    'pluginOptions' => [
				        'allowClear' => true,
				        'minimumInputLength' => 3,
				        'language' => [
				            'errorLoading' => new JsExpression("function () { return 'Waiting for results...'; }"),
				        ],
				        'ajax' => [
				            'url' => $airport_url,
				            'dataType' => 'json',
				            'data' => new JsExpression('function(params) { return {q:params.term}; }')
				        ],
				        'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
				        'templateResult' => new JsExpression('function(airport) { return airport.name; }'),
				        'templateSelection' => new JsExpression('function (airport) { return airport.name; }'),
				    ],
				]); 

			?>


		    <div class="form-group">
		    	<p class="text text-right">
			        <?= Html::a('Cancel', ['user/account'], ['class' => 'btn btn-sm btn-danger']) ?>	
			        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>	
		    	</p>
		    </div>

		    <?php ActiveForm::end(); ?>
		</div>
	</div>
</div>

frontend/views/user/account.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\i18n\Formatter;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = (Yii::$app->user->identity->firstname && Yii::$app->user->identity->lastname)?Yii::$app->user->identity->fullName():Yii::$app->user->identity->username;
$this->params['breadcrumbs'][] = $this->title;



?>
<div class="user-account">

    <div class="row">
        <div class="content-div" id="account-menu">
            <p><?= Html::a('About You', "#about-you", ['class' => 'btn btn-primary btn-block']) ?></p>
          <!----  <p><?= Html::a('Payment Methods', "#credit-cards", ['class' => 'btn btn-primary btn-block']) ?></p>---->
            <p><?= Html::a('Currency', "#currency", ['class' => 'btn btn-primary btn-block']) ?></p>
            <p><?= Html::a('Password', "#password", ['class' => 'btn btn-primary btn-block']) ?></p>
           <!----<p><?= Html::a('Social networks', "#social-networks", ['class' => 'btn btn-primary btn-block']) ?></p>---->
           <!---- <p><?= Html::a('Newsletter', "#newsletter", ['class' => 'btn btn-primary btn-block']) ?></p>--->
            <hr>
           <!---- <p><?= Html::a('My Trips', ['user/trips'], ['class' => 'btn btn-success btn-block disabled']) ?></p>--->
           <!---- <p><?= Html::a('Support Tickets', ['ticket/index'], ['class' => 'btn btn-success btn-block']) ?></p>--->
            <hr>
            <p><?= Html::a('Logout', ['site/logout'], ['class' => 'btn btn-danger btn-block', 'data-method' => 'post']) ?></p>
        </div>
        <div class="col-xs-10 col-xs-offset-2">
            <div class="content-div">
                <h2 id="about-you">You on eSports Travel</h2>
                <p>These details will auto-fill in forms and searches across the site. They are also displayed next to your publicly shared reviews, ratings, and comments. </p>
                <p class="text text-right"><?= Html::a('Update', ['update'], ['class' => 'btn btn-primary']) ?></p>

                <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        'username',
                        'email',
                        'firstname',
                        'middlename',
                        'lastname',
                        'phone',
                        'gender',
                        [                      // the owner name of the model
                            'label' => 'Country',
                            'value' => ($model->country)?$model->country->name . " (" . $model->country->code . ")":NULL,
                        ],
                        'date_of_birth:date:Date of birth',
                        [                      // the owner name of the model
                            'label' => 'Default Airport',
                            'value' => ($model->airport)?$model->airport->name . ", " . $model->airport->city . ", " . $model->airport->country . " - " . $model->airport->iata_code:NULL,
                        ],
                        'created_at:date:Joined on',
                    ],
                ]) ?>
            </div>
           <!----  <hr>
            <div class="content-div">
                <h2 id="credit-cards">Payment Methods</h2>
                <p>We do not currently store any of your payment details on our server.</p>
                <p class="text text-right"><?= Html::a('Add a card', ['add-card'], ['class' => 'btn btn-primary disabled']) ?></p>
            </div> ---->
            <hr>
            <div class="content-div">
                <h2 id="currency">Currency</h2>
                <p>At the moment the only supported currency is USD.</p>
            </div>
            <hr>
            <div class="content-div">
                <h2 id="password">Password</h2>
                <p>Would you like to change your password? Click the button below and we'll send you an email with a link to reset it.</p>
                <p><?= Html::a('Change password', ['user/request-password-reset'], ['class' => 'btn btn-primary']) ?></p>
            </div>
            <!----<hr>
            <div class="content-div">
                <h2 id="social-networks">Social networks</h2>
                <p>Coming soon</p>
            </div>
            <hr>
            <div class="content-div">
                <h2 id="newsletter">Newsletter preferences</h2>
                <p>Don't miss out on the best eSPORTS travel deals that we have to offer! How often you'd like to receive emails containing deals, events and recommendations?</p>
            </div>
            <hr>---->
			<br>
            <p class="text text-center">
                <small><?= Html::a('Click here', ['user/delete', 'id' => Yii::$app->user->id], ['class' => '', 'data-method' => 'post', 'data-confirm' => 'Are you sure you want to delete your account?']) ?> to delete your Esports Travel account.</small>
            </p>
        </div>
    </div>
</div>

frontend/views/user/confirmDeletion.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ConfirmDeletion */

$this->title = 'Confirm account deletion';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please confirm your action to <strong>delete</strong> your account by typing in your e-mail.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'confirm-deletion-form']); ?>
                <?= $form->field($model, 'email') ?>
                <div class="form-group">
                    <?= Html::submitButton('Confirm', ['class' => 'btn btn-danger']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/user/requestPasswordResetToken.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email in the form below. A link to reset password will be sent there provided it's the same e-mail you registered with.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>
                <?= $form->field($model, 'email') ?>
                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/user/resetPassword.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Type your new password in the form below:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\User */

$this->title = 'Update your account details';
$this->params['breadcrumbs'][] = ['label' => (Yii::$app->user->identity->firstname && Yii::$app->user->identity->lastname)?Yii::$app->user->identity->fullName():Yii::$app->user->identity->username, 'url' => ['account']];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="account-update content-div">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>