common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use backend\models\Ticket;
use common\models\Airport;
use common\models\Country;
use frontend\models\BookedFlight;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_ACTIVE = 1;
    const STATUS_BANNED = 2;

    const ROLE_CLIENT = 1;
    const ROLE_ADMIN = 2;

    const NEWSLETTER_DAILY = 'daily';
    const NEWSLETTER_WEEKLY = 'weekly';
    const NEWSLETTER_MONTHLY = 'monthly';
    const NEWSLETTER_EVENT = 'events';
    const NEWSLETTER_OFF = 'off';

    const USER = 'USER';
    const ADMIN = 'ADMIN';

    const NOT_DELETED = 0;
    const DELETED = 1;

    public $default_origin_airport_id;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    \yii\db\ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    \yii\db\ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                    ],
                'value' => new \yii\db\Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['airport_id'], 'integer'],
            [['country_id'], 'integer'],
            [['status'], 'integer'],
            [['status'], 'default', 'value' => self::STATUS_ACTIVE],
            [['role'], 'integer'],
            [['role'], 'default', 'value' => self::ROLE_CLIENT],
            [['email'], 'email'],
            [['date_of_birth'], 'date', 'format' => 'yyyy-mm-dd'],
            [['firstname'], 'string', 'max' => 90],
            [['middlename'], 'string', 'max' => 90],
            [['lastname'], 'string', 'max' => 90],
            [['phone'], 'string', 'max' => 90],
            [['gender'], 'in', 'range' => ['M', 'F']],
            [['newsletter'], 'default', 'value' => self::NEWSLETTER_WEEKLY],
            [['newsletter'], 'in', 'range' => ['daily', 'weekly', 'monthly', 'event', 'off']],
        ];
    }


    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'username' => 'Username',
            'firstname' => 'First name',
            'middlename' => 'Middle name',
            'lastname' => 'Last name',
            'phone' => 'Phone',
            'airport_id' => 'Your Default Airport (name, city or code)',
            'country_id' => 'Country',
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE, 'deleted' => self::NOT_DELETED]);
    }

    /**
     * Finds user by email
     *
     * @param string $email
     * @return static|null
     */
    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    public function selfDelete()
    {
        $this->deleted = self::DELETED;
    }

    public function selfUnDelete()
    {
        $this->deleted = self::NOT_DELETED;
    }

    public function countTickets()
    {
        $my_tickets = (new \yii\db\Query())
                    ->select('id')
                    ->from('ticket')
                    ->where(['admin_id' => $this->id, 'status' => [Ticket::STATUS_ASSIGNED]])
                    ->count();

        return $my_tickets;
    }

    public function fullName()
    {
        return $this->firstname . " " . $this->lastname;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAirport()
    {
        return $this->hasOne(Airport::className(), ['id' => 'airport_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCountry()
    {
        return $this->hasOne(Country::className(), ['id' => 'country_id']);
    }

}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;
use backend\models\search\BookingSearch;
use backend\models\search\EventSearch;
use backend\models\search\CommentSearch;
use backend\models\User;


/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
					[
                        'actions' => ['index'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            return !Yii::$app->user->isGuest && Yii::$app->user->identity->role==2;
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {

        $bookingSearchModel = new BookingSearch();
        $bookingDataProvider = $bookingSearchModel->listLatest();
        $eventSearchModel = new EventSearch();
        $eventDataProvider = $eventSearchModel->listLatest();
        $commentSearchModel = new CommentSearch();
        $commentDataProvider = $commentSearchModel->listLatest();

        return $this->render('index', [
            'bookingSearchModel' => $bookingSearchModel,
            'bookingDataProvider' => $bookingDataProvider,
            'eventSearchModel' => $eventSearchModel,
            'eventDataProvider' => $eventDataProvider,
            'commentSearchModel' => $commentSearchModel,
            'commentDataProvider' => $commentDataProvider,
            ]);
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
			if(!Yii::$app->user->isGuest && Yii::$app->user->identity->role!=2) {
				Yii::$app->user->logout();
				return $this->render('../site/error', [
					'name' => "Error 322",
					'message' => "You aren't permitted to view to the backend.",
				]);
			}
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\Event;
use frontend\models\FaregrabbrFlightForm;
use common\models\faregrabbr\HotelSearchForm;
use common\models\faregrabbr\FlightHotelSearchForm;
use frontend\models\search\CarouselSearch;
use frontend\models\search\EventSearch;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\UnauthorizedHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\adapters\FaregrabbrFlight;
use yii\helpers\Json;
use frontend\models\Article;
use frontend\models\News;
use frontend\models\search\ArticleSearch;
use frontend\models\search\NewsSearch;
use frontend\models\ArticleComment;
use frontend\models\search\ArticleCommentSearch;
use common\adapters\FaregrabbrHotelSearch;
use common\models\faregrabbr\HotelDetails;
use common\models\faregrabbr\HotelBookRequest;
use common\models\faregrabbr\Payment;
use common\models\faregrabbr\search\HotelSearch;
use common\models\faregrabbr\Passenger as FaregrabberPassenger;
use common\models\CreditCardForm;
use frontend\models\Guest;
use frontend\models\BookedHotel;
use frontend\models\Booking;
use yii\web\NotFoundHttpException;
use yii\data\Sort;
use yii\data\ArrayDataProvider;
use yii\web\GoneHttpException;
use common\adapters\FaregrabbrFlightSearch;
use common\models\faregrabbr\Flight;
use common\models\faregrabbr\FlightSearchForm;
use common\models\faregrabbr\search\FlightSearch;


/**
 * Site controller
 */
class SiteController extends Controller
{

    public static $carousels = null;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $articleSearchModel = new ArticleSearch();
        $newsSearchModel = new NewsSearch();
        $articleDataProvider = $articleSearchModel->search(Yii::$app->request->queryParams);
        $newsDataProvider = $newsSearchModel->search(Yii::$app->request->queryParams);
		$listOfEvents = Event::find()->where(['deleted' => Event::NOT_DELETED])->andWhere("start_time > NOW()")->orderBy('start_time')->all();

        $carouselSearchModel = new CarouselSearch();
        if (is_null(self::$carousels)) {
            self::$carousels = $carouselSearchModel->returnCarousels();
        }

        $nextEvent = $this->nextEvent();
		$hotelSearchForm = new HotelSearchForm();
		$flightSearchForm = new FlightSearchForm();
		$flightHotelSearchForm = new FlightHotelSearchForm();

        return $this->render('index', [
            'carousels' => self::$carousels,
            'articleSearchModel' => $articleSearchModel,
            'articleDataProvider' => $articleDataProvider,
            'newsSearchModel' => $newsSearchModel,
            'newsDataProvider' => $newsDataProvider,
			'listOfEvents' => $listOfEvents,
            'nextEvent' => $nextEvent,
			'hotelSearchForm' => $hotelSearchForm,
			'flightSearchForm' => $flightSearchForm,
			'flightHotelSearchForm' => $flightHotelSearchForm,
            ]);
    }

    public function actionEnter()
    {
        $signupForm = new SignupForm();
        $loginForm = new LoginForm();


        if ($signupForm->load(Yii::$app->request->post())) {
            if ($user = $signupForm->signup()) {
                if (Yii::$app->getUser()->login($user)) {
					$request = Yii::$app->request;
					$id = $request->get('booking_id');
					if($id != NULL) {
						return $this->redirect(['booking/view', 
						'id' => $id]);
					}
                    return $this->goHome();
                }
            }
        }

        if ($loginForm->load(Yii::$app->request->post()) && $loginForm->login()) {
            return $this->goBack();
        }

        return $this->render('enter', [
                'signupForm' => $signupForm,
                'loginForm' => $loginForm,
            ]);

    }

    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }
	
	    public function actionCorporate()
    {
          return $this->render('corporate');
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function nextEvent()
    {
        $event = Event::find()->where(['deleted' => Event::NOT_DELETED])->andWhere("start_time > NOW()")->orderBy('start_time')->one();
        return $event;
    }
}

frontend/views/site/_article.php
<?php
use yii\helpers\Url;

?>

<h2><a class="title-link" href="<?= Url::to(['article/view', 'id' => $model->id]); ?>"><?= $model->title ?></a></h2>
<p><small>Posted On: <?php echo Yii::$app->formatter->asDate($model->created_at, "long") ?> by <?php echo $model->admin->fullName(); ?></small></p>
<div class="article-body">
	<?= $model->body ?>
</div>
<div class="tags">
	<p class="tags"><small><?= $model->tags ?></small></p>
</div>
<div class="article-info">	
	<p>Comments: <strong><?= $model->countArticleComments() ?> </strong></p>
</div>

frontend/views/site/_event.php
<?php
use yii\helpers\Html;
use frontend\models\Event;

?>

<div class="col-sm-4">
	<div class="event" style="background-image: url('<?= $model->logo ?>'); background-position: center;">
	    <h2 class="text-center"><?php echo $model->name ?></h2>

	    <div class="event-info">
		    <p><?php echo $model->city . ", " . Event::$countries[$model->country] ?></p>
		    <p><?php echo $model->gamesString ?></p>
		    <p><?php echo $model->intro ?></p>
		    <p><?php echo Yii::$app->formatter->asDate($model->start_time, "php:d") . "-" . Yii::$app->formatter->asDate($model->end_time, "php:dS F Y") ?></p>
	    </div>

	    <p class="book"><?php echo (!Yii::$app->user->isGuest)?Html::a("<span class='glyphicon glyphicon-off'></span> Book Now", ['booking/create', 'event_id' => $model->id], ['class' => 'btn btn-block btn-power']):""; ?></p>
	    <p class="view"><?= Html::a("<span class='glyphicon glyphicon-off'></span> View Details", ['event/view', 'id' => $model->id], ['class' => 'btn btn-block btn-game']); ?></p>
	</div>

</div>

frontend/views/site/_eventSearch.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use frontend\models\Game;

/* @var $this yii\web\View */
/* @var $model frontend\models\search\EventSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="event-search col-sm-12">
    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => ['class' => 'form-horizontal row']
    ]); ?>

    <?= $form->field($model, 'name', ['options' => ['class' => 'col-sm-3'], 'inputOptions' => ['class' => 'form-control', 'placeholder' => 'Event Name']])->label(false) ?>

    <?= $form->field($model, 'city', ['options' => ['class' => 'col-sm-3'], 'inputOptions' => ['class' => 'form-control', 'placeholder' => 'City']])->label(false) ?>

    <?= $form->field($model, 'game.id', ['options' => ['class' => 'col-sm-3']])->dropDownList(Game::getDropDownArray())->label(false) ?>


    <div class="col-sm-3">

        <?= Html::submitButton('Filter', ['class' => 'btn col-sm-12 btn-travel']) ?>

    </div>

    <?php ActiveForm::end(); ?>
</div>

frontend/views/site/_news.php
<?php
use yii\helpers\Url;

?>

<a class="title-link" href="<?= Url::to(['news/view', 'id' => $model->id]); ?>"><h2><?= $model->title ?></h2></a> 
<p><small>Posted On: <?php echo Yii::$app->formatter->asDate($model->created_at, "long") ?> by <?php echo $model->admin->fullName(); ?></small></p>
<div class="news-body">
	<?= $model->body ?>
</div>
<div class="tags">
	<p class="tags"><small><?= $model->tags ?></small></p>
</div>
<div class="news-info">	
	<p>Comments: <strong><?= $model->countNewsComments() ?> </strong></p>
</div>

frontend/views/site/_quickSearch.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use frontend\models\Game;
use kartik\select2\Select2;
use yii\web\JsExpression;
use frontend\models\Event;

/* @var $this yii\web\View */
/* @var $model frontend\models\search\EventSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="event-search col-sm-12">
    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => ['class' => 'form-horizontal row']
    ]); ?>

    <?= $form->field($model, 'name', ['options' => ['class' => 'col-sm-3'], 'inputOptions' => ['class' => 'form-control', 'placeholder' => 'Event Name']])->label(false) ?>

    <?= $form->field($model, 'city', ['options' => ['class' => 'col-sm-3'], 'inputOptions' => ['class' => 'form-control', 'placeholder' => 'City']])->label(false) ?>

    <?= $form->field($model, 'game.id', ['options' => ['class' => 'col-sm-3']])->dropDownList(Game::getDropDownArray())->label(false) ?>


    <div class="col-sm-3">

        <?= Html::submitButton('Search', ['class' => 'btn col-sm-12 btn-travel']) ?>

    </div>

    <?php ActiveForm::end(); ?>
</div>

frontend/views/site/about.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>About us page</p>

</div>

frontend/views/site/contact.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-6 col-sm-offset-3">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'subject') ?>
                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>
                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-block btn-star', 'name' => 'contact-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/corporate.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Tabs;

/* @var $this yii\web\View */
//Add a comment to this line

$this->params['breadcrumbs'][] = "Corporate";
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

        <div class="col-lg-12 col-xs-12 col-sm-8">
         <?php

		echo '<iframe src="https://evo.faregrabbr.com/#/flights" name="evolution-main" width="100%" height="987" style="border:none;"></iframe>';
		 
		 
		 ?>
        
		</div>
</div>

frontend/views/site/enter.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $signupForm \frontend\models\SignupForm */

$this->title = 'Log In';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-enter">
    <div class="row">
        <div class="col-xs-12 col-sm-5">
    <h1>Sign up</h1>
            <p>Please fill out the following fields to signup:</p>

                    <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
                <div>
                        <?= $form->field($signupForm, 'username') ?>
                        <?= $form->field($signupForm, 'email') ?>
                        <?= $form->field($signupForm, 'password')->passwordInput() ?>
                        <?= $form->field($signupForm, 'password_repeat')->passwordInput() ?>
                </div>
                <div>
                        <?= $form->field($signupForm, 'verifyCode')->widget(Captcha::className(), [
                            'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                        ]) ?>
                </div>
                <div class="col-xs-12">            
                        <div class="form-group">
                            <?= Html::submitButton('Signup', ['class' => 'btn btn-star', 'name' => 'signup-button']) ?>
                        </div>
                </div>
                    <?php ActiveForm::end(); ?>
        </div>
        <div class="col-xs-12 col-sm-5 col-sm-offset-2">
            <h1>Log In</h1>
            <p>Or fill out the following fields to login:</p>
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
                <?= $form->field($loginForm, 'username') ?>
                <?= $form->field($loginForm, 'password')->passwordInput() ?>
                <?= $form->field($loginForm, 'rememberMe')->checkbox() ?>
                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['user/request-password-reset']) ?>.
                </div>
                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-star', 'name' => 'login-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
                <?= $form->field($model, 'username') ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
                <?= $form->field($model, 'rememberMe')->checkbox() ?>
                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>
                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-star', 'name' => 'login-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>